### ISSUE TITLE
Documentation for BIOS settings are still missing

### ISSUE THREAD

**Issue by DevHybrid-DE** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#1]
@SchmockLord : Very good documentation so far. Keep up your good work!
Could you please add missing parts - in Installation Step No.8 -BIOS Documentation- the documentation for the BIOS settings are still not uploaded into Github.

(https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3/blob/master/bios-settings.md).

**Comment by SchmockLord** [comment]
Added the BIOS settings

**Comment by fidalgodev** [comment]
Just want to say thank you @SchmockLord!

Amazing work. Any plans for future updates? On the Thunderbolt section you have TBD, but I have this exact board with a 10600K and a Gigabyte RX5700 XT and with this files everything works, even thunderbolt I think.

Also you say every USB port works, but doesn't MacOS limit you to 15 USB entries?

**Comment by SchmockLord** [comment]
@fidalgodev Thanks. The tbd in the Thunderbolt section was set, because I wanted to add screenshots from my BIOS TB settings. Just updated that. Thunderbolt 3 was already working.

Yeah, because this motherboard doesn't exceed the 15 port limit.

**Comment by fidalgodev** [comment]
> @fidalgodev Thanks. The tbd in the Thunderbolt section was set, because I wanted to add screenshots from my BIOS TB settings. Just updated that. Thunderbolt 3 was already working.
> 
> Yeah, because this motherboard doesn't exceed the 15 port limit.

Sick! Thank you! You have a paypal link I can donate some money to?

I have a very very weird "issue", whenever I move my mouse for example on the Dock icons, or basically any "link/button", there is a weird noise coming from the hardware, like coil whine noise... But when I bot on Windows (I have dual boot), this doesn't happen at all. This is super hard to figure out what the problem is, so just wondering if you have any idea.

Even with all the fans off. Seems like it's coming from the CPU or Ram

**Comment by SchmockLord** [comment]
Thanks. Yeah: paypal.me/ChristopherStarke

Because of the coil whine noise: I think it is the nvme SSD if you have one. I have noticed that for myself. I have a Intel 66p, a Samsung Evo 960 and a Samsung Evo 970. I think it is one of the samsungs because the intel is external, the samsungs are internal and it comes from the case.

**Comment by fidalgodev** [comment]
> Thanks. Yeah: paypal.me/ChristopherStarke
> 
> Because of the coil whine noise: I think it is the nvme SSD if you have one. I have noticed that for myself. I have a Intel 66p, a Samsung Evo 960 and a Samsung Evo 970. I think it is one of the samsungs because the intel is external, the samsungs are internal and it comes from the case.

I have 2 NVME SSD's. One on the front for Windows, and one on the back for the MacOS. They're both Crucial P5 500GB.
Weird that it doesn't happen on Windows tho

**Comment by fidalgodev** [comment]
> Thanks. Yeah: paypal.me/ChristopherStarke
> 
> Because of the coil whine noise: I think it is the nvme SSD if you have one. I have noticed that for myself. I have a Intel 66p, a Samsung Evo 960 and a Samsung Evo 970. I think it is one of the samsungs because the intel is external, the samsungs are internal and it comes from the case.

Also I was just checking and I'm 100% sure the sound is coming from the GPU, not the SSD. The SSD is on the back, and there is no sound coming from there. It's from the GPU
