### ISSUE TITLE
USB 2.0 Front Panel Header Not Working

### ISSUE THREAD

**Issue by malibio** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#13]
First of all, thank you for making this available. Everything worked practically seamlessly! The issues I've have had, is usually due to something I missed, etc.

On to my issue...I probably already have the answer to this question, but thought I would ask first:

There's a set of USB 2.0 header pins on the riser card (where the M.2 slot is located). I'm using this for my case and works during boot (recognized even by the MB to boot from). However, once I'm in the OS, it's not recognized anywhere (though the light is on).

My assumption is that this port wasn't included in the USB port mapping you've done. If so, has the limit been reached? Would I have have to create my own USB mapping kext?

T

**Comment by SchmockLord** [comment]
You are right. I might have disabled them because I don't use them and didn't notice that.

Can you please disable SSDT-UIAC.aml, plugin something in the USB 2.0 headers and tell me which HSxx ports are green in Hackintool after doing so?

Then I will adjust my config and you can test it again. So everyone participates.

**Comment by malibio** [comment]
I have to run an errand now, but will do it later today...thanks!

**Comment by malibio** [comment]
OK, so the one that had just turned on was HS01...

![image](https://user-images.githubusercontent.com/3272436/95744392-7d7cf880-0c93-11eb-870d-0d2034e45d72.png)

**Comment by SchmockLord** [comment]
Thanks. That helps and explains everything, because I removed HS01.

Can you please try this one. I have added the HS01 to this USB-port mapping:

[SSDT-UIAC-ASROCK-Z490-ITX-TB3.aml.zip](https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3/files/5365183/SSDT-UIAC-ASROCK-Z490-ITX-TB3.aml.zip)

**Comment by malibio** [comment]
The only other USB header is the USB 3.2 Gen 1 Header.

![image](https://user-images.githubusercontent.com/3272436/95748512-61c92080-0c9a-11eb-9b8f-7a3f1a1bbbcb.png)

![image](https://user-images.githubusercontent.com/3272436/95748558-6f7ea600-0c9a-11eb-9a9f-e34ee13d0270.png)

![image](https://user-images.githubusercontent.com/3272436/95748619-8b824780-0c9a-11eb-90da-9db0a2402bab.png)

![image](https://user-images.githubusercontent.com/3272436/95748373-2d556480-0c9a-11eb-9cd1-1c1635152ea6.png)

**Comment by malibio** [comment]
Just tried the UIAC file, and it works!

Thanks again @SchmockLord!

**Comment by SchmockLord** [comment]
Thanks for bringing that up :)
