### ISSUE TITLE
Poor mic quality via Bluetooth

### ISSUE THREAD

**Issue by fidalgodev** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#23]
I have terrible mic quality when using bluetooth headphones.
Tried with Airpods and Sony WH MX1000 3

When I use my macbook, the quality of the mic on the airpods/sony headphones is so much better.

But when using my hackintosh everyone complains about my mic, it's like im inside a box.
I'm using a BCM94360CD with external antennas, so it's a native MacOS card.

I saw more people with this issue with Hackintosh's, so just checking if you have any ideas?

https://www.reddit.com/r/hackintosh/comments/gfhmxk/improve_bluetooth_mic_audio_quality/

**Comment by fidalgodev** [comment]
Can this, in any way, be related to the USB power on the mini pci slot? (where the wifi/bt card plugs in)

**Comment by lctncld** [comment]
@fidalgodev did you manage to come up with a solution?

**Comment by fidalgodev** [comment]
Nope. I also dont get it since the WIFI/BT card I use is native to MacOS. But yeah my voice is very bad/robotic when using bluetooth mic. Tried with Airpods and Sony WH1000 MX3

**Comment by lctncld** [comment]
I guess this is the limitation of the chip. I have BCM94360NG and it has the same set of probIems. In HFP profile headphones are forced to 8kHz mode instead of 16kHz like they do on relatively new Macs. And the range is not the greatest in A2DP profile too.
I also tested the stock Intel card with [IntelBluetoothFirmware](https://github.com/OpenIntelWireless/IntelBluetoothFirmware) kext and headset profile is not supported at the moment at all, meaning you can't use mic with it.
What's worse is that I didn't really find _any_ success reports on the mic problem among any hackintosh build reports with Broadcom cards...

**Comment by fidalgodev** [comment]
Yeah, I dont think there are new WIFI/BT cards that are compatible with Hackintosh. The best is BCM94360CD but still has this issue (i have this one)
