### ISSUE TITLE
Ethernet not working out of the box

### ISSUE THREAD

**Issue by fidalgodev** [SchmockLord/Hackintosh-Intel-i9-10900k-AsRock-Z490-Phantom-ITX-TB3#4]
After having the same settings as described, ethernet does not work out of the box.

For people with the same issue, just go to:

System Preferences -> Network -> Select Ethernet -> click Advanced -> click Hardware -> Select Configure : Manually with Speed : 1000baseT.

After doing this ethernet worked for me. Not sure if you had to do this or not, but I guess so since I also saw this problem with another person using this board:
https://www.reddit.com/r/hackintosh/comments/i3pega/z490_itx_guide/

Perhaps you can add this to the docs as well? 😄

**Comment by fidalgodev** [comment]
@SchmockLord not sure if you had to do the same? I guess so since I used your exact config.
Maybe add this to the docs and we can close this issue too?

**Comment by malibio** [comment]
I had to do the same here. Thanks for pointing this out, @fidalgodev!

**Comment by SchmockLord** [comment]
I didn't have this issue.

My Hackintosh is connected to a 10Gbit NAS. And it was automatically detected with the 2.5GBit.

Maybe this happens when the 2.5GBit is connected to 1GBit device.

![Screen Shot 2020-10-12 at 13 40 26](https://user-images.githubusercontent.com/19785918/95742678-a8b21880-0c90-11eb-8617-45a3e2cd3369.png)
![Screen Shot 2020-10-12 at 13 41 01](https://user-images.githubusercontent.com/19785918/95742682-a9e34580-0c90-11eb-9fdd-9f8dbe7b685e.png)

**Comment by fidalgodev** [comment]
Might be yeah. Worth maybe add this to the readme in case people have this problem?
